version: '2'
services:
  jenkins:
    build: ./jenkins-master/
    networks:
      - jenkins
    ports:
      - '10800:10800'
      - '11080:11080'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  jenkins:
volumes:
  jenkins_data:
    driver: local